[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 4.4.0-210-generic (buildd@lgw01-amd64-009) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 (Ubuntu 4.4.0-210.242-generic 4.4.262)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-210-generic root=LABEL=cloudimg-rootfs ro console=tty1 console=ttyS0
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Centaur CentaurHauls
[    0.000000] [Firmware Bug]: TSC doesn't count with P0 frequency!
[    0.000000] x86/fpu: Legacy x87 FPU detected.
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000003ffeffff] usable
[    0.000000] BIOS-e820: [mem 0x000000003fff0000-0x000000003fffffff] ACPI data
[    0.000000] BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fee00000-0x00000000fee00fff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] SMBIOS 2.5 present.
[    0.000000] Hypervisor detected: KVM
[    0.000000] Kernel/User page tables isolation: disabled
[    0.000000] e820: last_pfn = 0x3fff0 max_arch_pfn = 0x400000000
[    0.000000] MTRR: Disabled
[    0.000000] x86/PAT: MTRRs disabled, skipping PAT initialization too.
[    0.000000] CPU MTRRs all blank - virtualized system.
[    0.000000] x86/PAT: Configuration [0-7]: WB  WT  UC- UC  WB  WT  UC- UC  
[    0.000000] found SMP MP-table at [mem 0x0009fff0-0x0009ffff] mapped at [ffff88000009fff0]
[    0.000000] Scanning 1 areas for low memory corruption
[    0.000000] RAMDISK: [mem 0x3613c000-0x37095fff]
[    0.000000] ACPI: Early table checksum verification disabled
[    0.000000] ACPI: RSDP 0x00000000000E0000 000024 (v02 VBOX  )
[    0.000000] ACPI: XSDT 0x000000003FFF0030 00003C (v01 VBOX   VBOXXSDT 00000001 ASL  00000061)
[    0.000000] ACPI: FACP 0x000000003FFF00F0 0000F4 (v04 VBOX   VBOXFACP 00000001 ASL  00000061)
[    0.000000] ACPI: DSDT 0x000000003FFF0470 002325 (v02 VBOX   VBOXBIOS 00000002 INTL 20100528)
[    0.000000] ACPI: FACS 0x000000003FFF0200 000040
[    0.000000] ACPI: FACS 0x000000003FFF0200 000040
[    0.000000] ACPI: APIC 0x000000003FFF0240 00005C (v02 VBOX   VBOXAPIC 00000001 ASL  00000061)
[    0.000000] ACPI: SSDT 0x000000003FFF02A0 0001CC (v01 VBOX   VBOXCPUT 00000002 INTL 20100528)
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at [mem 0x0000000000000000-0x000000003ffeffff]
[    0.000000] NODE_DATA(0) allocated [mem 0x3ffeb000-0x3ffeffff]
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: cpu 0, msr 0:3ffe3001, primary cpu clock
[    0.000000] kvm-clock: using sched offset of 4082424354 cycles
[    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[    0.000000]   DMA32    [mem 0x0000000001000000-0x000000003ffeffff]
[    0.000000]   Normal   empty
[    0.000000]   Device   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000001000-0x000000000009efff]
[    0.000000]   node   0: [mem 0x0000000000100000-0x000000003ffeffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000001000-0x000000003ffeffff]
[    0.000000] ACPI: PM-Timer IO Port: 0x4008
[    0.000000] IOAPIC[0]: apic_id 2, version 32, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 low level)
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] smpboot: Allowing 2 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: [mem 0x00000000-0x00000fff]
[    0.000000] PM: Registered nosave memory: [mem 0x0009f000-0x0009ffff]
[    0.000000] PM: Registered nosave memory: [mem 0x000a0000-0x000effff]
[    0.000000] PM: Registered nosave memory: [mem 0x000f0000-0x000fffff]
[    0.000000] e820: [mem 0x40000000-0xfebfffff] available for PCI devices
[    0.000000] Booting paravirtualized kernel on KVM
[    0.000000] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645519600211568 ns
[    0.000000] setup_percpu: NR_CPUS:512 nr_cpumask_bits:512 nr_cpu_ids:2 nr_node_ids:1
[    0.000000] PERCPU: Embedded 33 pages/cpu @ffff88003fc00000 s95192 r8192 d31784 u1048576
[    0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 257912
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-210-generic root=LABEL=cloudimg-rootfs ro console=tty1 console=ttyS0
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Memory: 996960K/1048120K available (8644K kernel code, 1332K rwdata, 4044K rodata, 1492K init, 1164K bss, 51160K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] 	Build-time adjustment of leaf fanout to 64.
[    0.000000] 	RCU restricting CPUs from NR_CPUS=512 to nr_cpu_ids=2.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=64, nr_cpu_ids=2
[    0.000000] NR_IRQS:33024 nr_irqs:440 16
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [tty1] enabled
[    0.000000] console [ttyS0] enabled
[    0.000000] tsc: Detected 3593.100 MHz processor
[    0.634875] Calibrating delay loop (skipped) preset value.. 7186.20 BogoMIPS (lpj=14372400)
[    0.644394] pid_max: default: 32768 minimum: 301
[    0.649819] ACPI: Core revision 20150930
[    0.655865] ACPI: 2 ACPI AML tables successfully acquired and loaded
[    0.664475] Security Framework initialized
[    0.669409] Yama: becoming mindful.
[    0.674279] AppArmor: AppArmor initialized
[    0.678337] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.691027] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.702740] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.711405] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.721340] Initializing cgroup subsys io
[    0.725223] Initializing cgroup subsys memory
[    0.729613] Initializing cgroup subsys devices
[    0.733938] Initializing cgroup subsys freezer
[    0.738119] Initializing cgroup subsys net_cls
[    0.742547] Initializing cgroup subsys perf_event
[    0.747602] Initializing cgroup subsys net_prio
[    0.753934] Initializing cgroup subsys hugetlb
[    0.758356] Initializing cgroup subsys pids
[    0.763799] mce: CPU supports 0 MCE banks
[    0.767798] Last level iTLB entries: 4KB 1024, 2MB 1024, 4MB 512
[    0.773538] Last level dTLB entries: 4KB 1536, 2MB 1536, 4MB 768, 1GB 0
[    0.780419] Spectre V1 : Mitigation: usercopy/swapgs barriers and __user pointer sanitization
[    0.789412] Spectre V2 : Spectre mitigation: LFENCE not serializing, switching to generic retpoline
[    0.799352] Spectre V2 : Mitigation: Full generic retpoline
[    0.804502] Spectre V2 : Spectre v2 / SpectreRSB mitigation: Filling RSB on context switch
[    0.849516] Freeing SMP alternatives memory: 36K
[    0.941775] ftrace: allocating 32380 entries in 127 pages
[    1.579191] smpboot: APIC(0) Converting physical 0 to logical package 0
[    1.586515] smpboot: Max logical packages: 1
[    1.603923] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    1.718473] smpboot: CPU0: AMD Ryzen 5 2400G with Radeon Vega Graphics (family: 0x17, model: 0x11, stepping: 0x0)
[    1.730390] Performance Events: Broken PMU hardware detected, using software events only.
[    1.738349] Failed to access perfctr msr (MSR c0010007 is 0)
[    1.834041] KVM setup paravirtual spinlock
[    1.840462] x86: Booting SMP configuration:
[    1.844293] .... node  #0, CPUs:      #1
[    1.849314] kvm-clock: cpu 1, msr 0:3ffe3041, secondary cpu clock
[    1.855809] mce: CPU supports 0 MCE banks
[    1.860176] TSC synchronization [CPU#0 -> CPU#1]:
[    1.864566] Measured 145400 cycles TSC warp between CPUs, turning off TSC clock.
[    1.870875] tsc: Marking TSC unstable due to check_tsc_sync_source failed
[    0.541560] x86: Booted up 1 node, 2 CPUs
[    0.544005] smpboot: Total of 2 processors activated (14372.40 BogoMIPS)
[    0.556117] devtmpfs: initialized
[    0.561002] evm: security.selinux
[    0.564002] evm: security.SMACK64
[    0.566975] evm: security.SMACK64EXEC
[    0.568003] evm: security.SMACK64TRANSMUTE
[    0.572003] evm: security.SMACK64MMAP
[    0.576003] evm: security.ima
[    0.580003] evm: security.capability
[    0.584230] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.588076] futex hash table entries: 512 (order: 3, 32768 bytes)
[    0.596153] pinctrl core: initialized pinctrl subsystem
[    0.600391] RTC time: 12:34:18, date: 08/10/22
[    0.605082] NET: Registered protocol family 16
[    0.624007] cpuidle: using governor ladder
[    0.640008] cpuidle: using governor menu
[    0.648013] PCCT header not found.
[    0.661433] ACPI: bus type PCI registered
[    0.668006] acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5
[    0.676181] PCI: Using configuration type 1 for base access
[    0.680002] PCI: Using configuration type 1 for extended access
[    0.700347] ACPI: Added _OSI(Module Device)
[    0.708008] ACPI: Added _OSI(Processor Device)
[    0.712004] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.716009] ACPI: Added _OSI(Processor Aggregator Device)
[    0.721255] ACPI: Executed 1 blocks of module-level executable AML code
[    0.736079] ACPI: Interpreter enabled
[    0.739872] ACPI: (supports S0 S5)
[    0.744006] ACPI: Using IOAPIC for interrupt routing
[    0.748399] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    0.765297] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[    0.768023] acpi PNP0A03:00: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI]
[    0.780403] acpi PNP0A03:00: _OSC: platform does not support [PCIeCapability]
[    0.784723] acpi PNP0A03:00: _OSC: not requesting control; platform does not support [PCIeCapability]
[    0.796007] acpi PNP0A03:00: _OSC: OS requested [PCIeHotplug PME AER PCIeCapability]
[    0.804008] acpi PNP0A03:00: _OSC: platform willing to grant [PCIeHotplug PME AER]
[    0.808005] acpi PNP0A03:00: _OSC failed (AE_SUPPORT); disabling ASPM
[    0.816777] PCI host bridge to bus 0000:00
[    0.820010] pci_bus 0000:00: root bus resource [io  0x0000-0x0cf7 window]
[    0.828006] pci_bus 0000:00: root bus resource [io  0x0d00-0xffff window]
[    0.832005] pci_bus 0000:00: root bus resource [mem 0x000a0000-0x000bffff window]
[    0.840008] pci_bus 0000:00: root bus resource [mem 0x40000000-0xfdffffff window]
[    0.848005] pci_bus 0000:00: root bus resource [bus 00-ff]
[    0.878985] pci 0000:00:01.1: legacy IDE quirk: reg 0x10: [io  0x01f0-0x01f7]
[    0.884010] pci 0000:00:01.1: legacy IDE quirk: reg 0x14: [io  0x03f6]
[    0.892009] pci 0000:00:01.1: legacy IDE quirk: reg 0x18: [io  0x0170-0x0177]
[    0.896005] pci 0000:00:01.1: legacy IDE quirk: reg 0x1c: [io  0x0376]
[    0.924900] pci 0000:00:07.0: quirk: [io  0x4000-0x403f] claimed by PIIX4 ACPI
[    0.932054] pci 0000:00:07.0: quirk: [io  0x4100-0x410f] claimed by PIIX4 SMB
[    0.948821] ACPI: PCI Interrupt Link [LNKA] (IRQs 5 9 10 *11)
[    0.958202] ACPI: PCI Interrupt Link [LNKB] (IRQs 5 9 *10 11)
[    0.968215] ACPI: PCI Interrupt Link [LNKC] (IRQs 5 *9 10 11)
[    0.978789] ACPI: PCI Interrupt Link [LNKD] (IRQs 5 9 10 *11)
[    0.989252] ACPI: Enabled 2 GPEs in block 00 to 07
[    0.996251] vgaarb: setting as boot device: PCI:0000:00:02.0
[    1.000000] vgaarb: device added: PCI:0000:00:02.0,decodes=io+mem,owns=io+mem,locks=none
[    1.008007] vgaarb: loaded
[    1.012003] vgaarb: bridge control possible 0000:00:02.0
[    1.016652] SCSI subsystem initialized
[    1.020303] ACPI: bus type USB registered
[    1.024090] usbcore: registered new interface driver usbfs
[    1.028037] usbcore: registered new interface driver hub
[    1.032031] usbcore: registered new device driver usb
[    1.040424] PCI: Using ACPI for IRQ routing
[    1.044881] NetLabel: Initializing
[    1.048003] NetLabel:  domain hash size = 128
[    1.052005] NetLabel:  protocols = UNLABELED CIPSOv4
[    1.060020] NetLabel:  unlabeled traffic allowed by default
[    1.064148] amd_nb: Cannot enumerate AMD northbridges
[    1.072263] clocksource: Switched to clocksource kvm-clock
[    1.110877] AppArmor: AppArmor Filesystem Enabled
[    1.116207] pnp: PnP ACPI init
[    1.123371] pnp: PnP ACPI: found 3 devices
[    1.169325] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
[    1.177455] NET: Registered protocol family 2
[    1.182384] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[    1.189154] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
[    1.195901] TCP: Hash tables configured (established 8192 bind 8192)
[    1.202480] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    1.208131] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    1.214309] NET: Registered protocol family 1
[    1.218715] pci 0000:00:00.0: Limiting direct PCI/PCI transfers
[    1.224363] pci 0000:00:01.0: Activating ISA DMA hang workarounds
[    1.230728] Unpacking initramfs...
[    1.260520] Freeing initrd memory: 15720K
[    1.705578] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x33cadd673d5, max_idle_ns: 440795311064 ns
[    1.722468] platform rtc_cmos: registered platform RTC device (no PNP device found)
[    1.734339] Scanning for low memory corruption every 60 seconds
[    1.745640] audit: initializing netlink subsys (disabled)
[    1.751612] audit: type=2000 audit(1660134863.160:1): initialized
[    1.758089] Initialise system trusted keyring
[    1.764251] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    1.775157] zbud: loaded
[    1.780073] VFS: Disk quotas dquot_6.6.0
[    1.785419] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    1.794081] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    1.802587] fuse init (API version 7.23)
[    1.807824] Key type big_key registered
[    1.811782] Allocating IMA MOK and blacklist keyrings.
[    1.833301] Key type asymmetric registered
[    1.839337] Asymmetric key parser 'x509' registered
[    1.846088] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    1.856820] io scheduler noop registered
[    1.860576] io scheduler deadline registered (default)
[    1.865376] io scheduler cfq registered
[    1.869280] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    1.875323] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    1.883258] ACPI: AC Adapter [AC] (on-line)
[    1.888316] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[    1.896762] ACPI: Power Button [PWRF]
[    1.901523] input: Sleep Button as /devices/LNXSYSTM:00/LNXSLPBN:00/input/input1
[    1.909945] ACPI: Sleep Button [SLPF]
[    1.914259] GHES: HEST is not enabled!
[    1.918456] Serial: 8250/16550 driver, 32 ports, IRQ sharing enabled
[    1.950953] 00:02: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    1.978061] Linux agpgart interface v0.103
[    2.001114] loop: module loaded
[    2.009168] scsi host0: ata_piix
[    2.014320] scsi host1: ata_piix
[    2.017696] ata1: PATA max UDMA/33 cmd 0x1f0 ctl 0x3f6 bmdma 0xd000 irq 14
[    2.023722] ata2: PATA max UDMA/33 cmd 0x170 ctl 0x376 bmdma 0xd008 irq 15
[    2.031267] libphy: Fixed MDIO Bus: probed
[    2.036172] tun: Universal TUN/TAP device driver, 1.6
[    2.040111] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    2.049369] PPP generic driver version 2.4.2
[    2.056394] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    2.062601] ehci-pci: EHCI PCI platform driver
[    2.066965] ehci-platform: EHCI generic platform driver
[    2.071772] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    2.078192] ohci-pci: OHCI PCI platform driver
[    2.083004] ohci-platform: OHCI generic platform driver
[    2.089006] uhci_hcd: USB Universal Host Controller Interface driver
[    2.097044] i8042: PNP: PS/2 Controller [PNP0303:PS2K,PNP0f03:PS2M] at 0x60,0x64 irq 1,12
[    2.113203] serio: i8042 KBD port at 0x60,0x64 irq 1
[    2.116379] serio: i8042 AUX port at 0x60,0x64 irq 12
[    2.126191] mousedev: PS/2 mouse device common for all mice
[    2.138086] rtc_cmos rtc_cmos: rtc core: registered rtc_cmos as rtc0
[    2.148066] rtc_cmos rtc_cmos: alarms up to one day, 114 bytes nvram
[    2.156182] i2c /dev entries driver
[    2.156319] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input2
[    2.170962] device-mapper: uevent: version 1.0.3
[    2.176411] device-mapper: ioctl: 4.34.0-ioctl (2015-10-28) initialised: dm-devel@redhat.com
[    2.219370] ledtrig-cpu: registered to indicate activity on CPUs
[    2.227450] NET: Registered protocol family 10
[    2.233123] NET: Registered protocol family 17
[    2.238388] Key type dns_resolver registered
[    2.243874] registered taskstats version 1
[    2.248792] Loading compiled-in X.509 certificates
[    2.254929] Loaded X.509 cert 'Build time autogenerated kernel key: cf00e047681d67edb2720680708b7d9498083038'
[    2.264861] zswap: loaded using pool lzo/zbud
[    2.278176] Key type trusted registered
[    2.295379] Key type encrypted registered
[    2.300584] AppArmor: AppArmor sha1 policy hashing enabled
[    2.307467] ima: No TPM chip found, activating TPM-bypass!
[    2.312631] ima: Allocated hash algorithm: sha1
[    2.317276] evm: HMAC attrs: 0x1
[    2.322011]   Magic number: 2:66:582
[    2.327799] rtc_cmos rtc_cmos: setting system clock to 2022-08-10 12:34:19 UTC (1660134859)
[    2.338800] BIOS EDD facility v0.16 2004-Jun-25, 0 devices found
[    2.344332] EDD information not available.
[    2.350462] Freeing unused kernel memory: 1492K
[    2.364488] Write protecting the kernel read-only data: 14336k
[    2.372653] Freeing unused kernel memory: 1584K
[    2.379130] Freeing unused kernel memory: 52K
Loading, please wait...
starting version 229
[    2.416852] random: systemd-udevd: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.418019] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.418041] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.433915] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.433957] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.434151] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.434197] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.434308] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.434395] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.434443] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    2.543262] e1000: Intel(R) PRO/1000 Network Driver - version 7.3.21-k8-NAPI
[    2.549514] e1000: Copyright (c) 1999-2006 Intel Corporation.
[    2.572789] Fusion MPT base driver 3.04.20
[    2.579026] Copyright (c) 1999-2008 LSI Corporation
[    2.593741] [drm] Initialized drm 1.1.0 20060810
[    2.627845] Fusion MPT SPI Host driver 3.04.20
[    2.649130] vboxvideo: loading out-of-tree module taints kernel.
[    2.655677] vboxvideo: module verification failed: signature and/or required key missing - tainting kernel
[    2.669635] vboxvideo: loading version 6.1.36 r152435
[    2.830763] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input4
[    3.550935] e1000 0000:00:03.0 eth0: (PCI:33MHz:32-bit) 02:be:82:6b:cc:1d
[    3.560140] e1000 0000:00:03.0 eth0: Intel(R) PRO/1000 Network Connection
[    3.581298] mptbase: ioc0: Initiating bringup
[    3.679317] ioc0: LSI53C1030 A0: Capabilities={Initiator}
[    3.871373] scsi host2: ioc0: LSI53C1030 A0, FwRev=00000000h, Ports=1, MaxQ=256, IRQ=20
[    4.007072] scsi 2:0:0:0: Direct-Access     VBOX     HARDDISK         1.0  PQ: 0 ANSI: 5
[    4.019381] [drm] VRAM 01000000
[    4.025449] scsi target2:0:0: Beginning Domain Validation
[    4.036962] [TTM] Zone  kernel: Available graphics memory: 507922 kiB
[    4.048668] [TTM] Initializing pool allocator
[    4.059370] [TTM] Initializing DMA pool allocator
[    4.091245] scsi target2:0:0: Domain Validation skipping write tests
[    4.095207] scsi target2:0:0: Ending Domain Validation
[    4.113418] scsi target2:0:0: asynchronous
[    4.124898] fbcon: vboxdrmfb (fb0) is primary device
[    4.131238] scsi 2:0:1:0: Direct-Access     VBOX     HARDDISK         1.0  PQ: 0 ANSI: 5
[    4.131289] scsi target2:0:1: Beginning Domain Validation
[    4.148344] scsi target2:0:1: Domain Validation skipping write tests
[    4.148346] scsi target2:0:1: Ending Domain Validation
[    4.148884] scsi target2:0:1: asynchronous
[    4.177693] sd 2:0:0:0: [sda] 83886080 512-byte logical blocks: (42.9 GB/40.0 GiB)
[    4.179179] sd 2:0:0:0: Attached scsi generic sg0 type 0
[    4.180884] sd 2:0:1:0: [sdb] 20480 512-byte logical blocks: (10.5 MB/10.0 MiB)
[    4.181233] sd 2:0:1:0: Attached scsi generic sg1 type 0
[    4.181832] sd 2:0:1:0: [sdb] Write Protect is off
[    4.182394] sd 2:0:1:0: [sdb] Incomplete mode parameter data
[    4.182396] sd 2:0:1:0: [sdb] Assuming drive cache: write through
[    4.183981] Console: switching to colour frame buffer device 100x37
[    4.184077] sd 2:0:0:0: [sda] Write Protect is off
[    4.187506] sd 2:0:0:0: [sda] Incomplete mode parameter data
[    4.187508] sd 2:0:0:0: [sda] Assuming drive cache: write through
[    4.197016]  sda: sda1
[    4.210262] sd 2:0:0:0: [sda] Attached SCSI disk
[    4.211385] sd 2:0:1:0: [sdb] Attached SCSI disk
[    4.434473] vboxvideo 0000:00:02.0: fb0: vboxdrmfb frame buffer device
[    4.460682] [drm] Initialized vboxvideo 1.0.0 20130823 for 0000:00:02.0 on minor 0
[    5.275825] e1000 0000:00:08.0 eth1: (PCI:33MHz:32-bit) 08:00:27:77:6f:9f
[    5.290596] e1000 0000:00:08.0 eth1: Intel(R) PRO/1000 Network Connection
[    5.309762] e1000 0000:00:03.0 enp0s3: renamed from eth0
[    5.338049] e1000 0000:00:08.0 enp0s8: renamed from eth1
Begin: Loading essential drivers ... [    5.699475] md: linear personality registered for level -1
[    5.721778] md: multipath personality registered for level -4
[    5.744166] md: raid0 personality registered for level 0
[    5.775845] md: raid1 personality registered for level 1
[    5.864203] raid6: sse2x1   gen()  5596 MB/s
[    5.948152] raid6: sse2x1   xor()  5342 MB/s
[    6.032097] raid6: sse2x2   gen() 11787 MB/s
[    6.116223] raid6: sse2x2   xor()  8255 MB/s
[    6.200357] raid6: sse2x4   gen() 13711 MB/s
[    6.280179] raid6: sse2x4   xor()  6411 MB/s
[    6.295320] raid6: using algorithm sse2x4 gen() 13711 MB/s
[    6.312126] raid6: .... xor() 6411 MB/s, rmw enabled
[    6.328302] raid6: using ssse3x2 recovery algorithm
[    6.348426] xor: measuring software checksum speed
[    6.400703]    prefetch64-sse: 13173.000 MB/sec
[    6.452607]    generic_sse: 14030.000 MB/sec
[    6.467002] xor: using function: generic_sse (14030.000 MB/sec)
[    6.487443] async_tx: api initialized (async)
[    6.556826] md: raid6 personality registered for level 6
[    6.573011] md: raid5 personality registered for level 5
[    6.589487] md: raid4 personality registered for level 4
[    6.630331] md: raid10 personality registered for level 10
done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... [    6.744622] Btrfs loaded
Scanning for Btrfs filesystems
done.
Begin: Will now check root file system ... fsck from util-linux 2.27.1
[/sbin/fsck.ext4 (1) -- /dev/sda1] fsck.ext4 -a -C0 /dev/sda1 
cloudimg-rootfs: recovering journal
cloudimg-rootfs: clean, 65650/5120000 files, 611312/10485499 blocks
done.
[    7.034118] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
done.
Begin: Running /scripts/local-bottom ... done.
Begin: Running /scripts/init-bottom ... done.
[    7.281011] systemd[1]: Failed to insert module 'autofs4': No such file or directory
[    7.352787] systemd[1]: systemd 229 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN)
[    7.402024] systemd[1]: Detected virtualization oracle.
[    7.423095] systemd[1]: Detected architecture x86-64.

Welcome to [1mUbuntu 16.04.7 LTS[0m!

[    7.457527] systemd[1]: Set hostname to <web01>.
[    7.830757] systemd[1]: Created slice System Slice.
[[0;32m  OK  [0m] Created slice System Slice.
[    7.850222] systemd[1]: Listening on Journal Audit Socket.
[[0;32m  OK  [0m] Listening on Journal Audit Socket.
[    7.870073] systemd[1]: Reached target User and Group Name Lookups.
[[0;32m  OK  [0m] Reached target User and Group Name Lookups.
[    7.891243] systemd[1]: Created slice system-serial\x2dgetty.slice.
[[0;32m  OK  [0m] Created slice system-serial\x2dgetty.slice.
[    7.913320] systemd[1]: Started Trigger resolvconf update for networkd DNS.
[[0;32m  OK  [0m] Started Trigger resolvconf update for networkd DNS.
[    7.935254] systemd[1]: Listening on udev Kernel Socket.
[[0;32m  OK  [0m] Listening on udev Kernel Socket.
[    7.957294] systemd[1]: Listening on Syslog Socket.
[[0;32m  OK  [0m] Listening on Syslog Socket.
[    7.976807] systemd[1]: Starting of Arbitrary Executable File Formats File System Automount Point not supported.
[[0;1;33mUNSUPP[0m] Starting of Arbitrary Executable Fi...m Automount Point not supported.
[    8.023617] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[[0;32m  OK  [0m] Listening on /dev/initctl Compatibility Named Pipe.
[    8.051860] systemd[1]: Listening on udev Control Socket.
[[0;32m  OK  [0m] Listening on udev Control Socket.
[    8.081277] systemd[1]: Reached target Encrypted Volumes.
[[0;32m  OK  [0m] Reached target Encrypted Volumes.
[    8.110953] systemd[1]: Listening on fsck to fsckd communication Socket.
[[0;32m  OK  [0m] Listening on fsck to fsckd communication Socket.
[    8.140631] systemd[1]: Listening on Journal Socket (/dev/log).
[[0;32m  OK  [0m] Listening on Journal Socket (/dev/log).
[    8.167030] systemd[1]: Listening on Device-mapper event daemon FIFOs.
[[0;32m  OK  [0m] Listening on Device-mapper event daemon FIFOs.
[    8.193079] systemd[1]: Reached target Swap.
[[0;32m  OK  [0m] Reached target Swap.
[    8.217753] systemd[1]: Listening on LVM2 metadata daemon socket.
[[0;32m  OK  [0m] Listening on LVM2 metadata daemon socket.
[    8.244671] systemd[1]: Listening on Journal Socket.
[[0;32m  OK  [0m] Listening on Journal Socket.
[    8.284978] systemd[1]: Mounting Debug File System...
         Mounting Debug File System...
[    8.317669] systemd[1]: Starting Journal Service...
         Starting Journal Service...
[    8.348490] systemd[1]: Starting Nameserver information manager...
         Starting Nameserver information manager...
[    8.377077] systemd[1]: Starting Set console keymap...
         Starting Set console keymap...
[    8.411642] systemd[1]: Mounting Huge Pages File System...
         Mounting Huge Pages File System...
[    8.464818] systemd[1]: Starting Load Kernel Modules...
         Starting Load Kernel Modules...
[    8.491523] systemd[1]: Starting Remount Root and Kernel File Systems...
[    8.511407] random: nonblocking pool is initialized
         Starting Remount Root and Kernel File Systems...[    8.533841] EXT4-fs (sda1): re-mounted. Opts: (null)

[    8.542419] systemd[1]: Mounting POSIX Message Queue File System...
         Mounting POSIX Message Queue File System...
[    8.579225] systemd[1]: Listening on LVM2 poll daemon socket.
[[0;32m  OK  [0m] Listening on LVM2 poll daemon socket.
[    8.608101] systemd[1]: Starting Uncomplicated firewall...
         Starting Uncomplicated firewall...
[    8.636811] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
         Starting Monitoring of LVM2 mirrors... dmeventd or progress polling...
[    8.684792] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[[0;32m  OK  [0m] Started Forward Password Requests to Wall Directory Watch.
[    8.712706] systemd[1]: Starting Create Static Device Nodes in /dev...
         Starting Create Static Device Nodes in /dev...
[    8.738747] systemd[1]: Created slice User and Session Slice.
[[0;32m  OK  [0m] Created slice User and Session Slice.
[    8.768462] systemd[1]: Reached target Slices.
[[0;32m  OK  [0m] Reached target Slices.
[    8.813777] systemd[1]: Mounted Huge Pages File System.
[[0;32m  OK  [0m] Mounted Huge Pages File System.
[    8.838341] systemd[1]: Mounted POSIX Message Queue File System.
[[0;32m  OK  [0m] Mounted POSIX Message Queue File System.
[    8.861475] systemd[1]: Mounted Debug File System.
[[0;32m  OK  [0m] Mounted Debug File System.
[    8.887858] systemd[1]: Started Journal Service.
[[0;32m  OK  [0m] Started Journal Service.
[[0;32m  OK  [0m] Started Set console keymap.
[[0;1;31mFAILED[0m] Failed to start Load Kernel Modules.
See 'systemctl status systemd-modules-load.service' for details.
[[0;32m  OK  [0m] Started Remount Root and Kernel File Systems.
[[0;32m  OK  [0m] Started Uncomplicated firewall.
[[0;32m  OK  [0m] Started Create Static Device Nodes in /dev.
[[0;32m  OK  [0m] Started Nameserver information manager.
[[0;32m  OK  [0m] Started LVM2 metadata daemon.
         Starting udev Kernel Device Manager...
         Starting udev Coldplug all Devices...
         Starting Load/Save Random Seed...
         Starting Apply Kernel Variables...
         Mounting FUSE Control File System...
         Starting Flush Journal to Persistent Storage...
[[0;32m  OK  [0m] Mounted FUSE Control File System.
[[0;32m  OK  [0m] Started Load/Save Random Seed.
[[0;32m  OK  [0m] Started Monitoring of LVM2 mirrors,...ng dmeventd or progress polling.
[[0;32m  OK  [0m] Started Apply Kernel Variables.
[[0;32m  OK  [0m] Started udev Coldplug all Devices.
[[0;32m  OK  [0m] Reached target Local File Systems (Pre).
[[0;32m  OK  [0m] Reached target Local File Systems.
         Starting Set console font and keymap...
         Starting Tell Plymouth To Write Out Runtime Data...
         Starting LSB: AppArmor initialization...
         Starting Initial cloud-init job (pre-networking)...
[[0;32m  OK  [0m] Started udev Kernel Device Manager.
[[0;32m  OK  [0m] Started Flush Journal to Persistent Storage.
[[0;32m  OK  [0m] Started Tell Plymouth To Write Out Runtime Data.
         Starting Create Volatile Files and Directories...
[[0;32m  OK  [0m] Started Dispatch Password Requests to Console Directory Watch.
[[0;32m  OK  [0m] Started Create Volatile Files and Directories.
[[0;32m  OK  [0m] Reached target System Time Synchronized.
         Starting Update UTMP about System Boot/Shutdown...
[[0;32m  OK  [0m] Started Update UTMP about System Boot/Shutdown.
[[0;32m  OK  [0m] Found device /dev/ttyS0.
[[0;32m  OK  [0m] Started Set console font and keymap.
[[0;32m  OK  [0m] Created slice system-getty.slice.
[[0;32m  OK  [0m] Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
[[0;32m  OK  [0m] Started LSB: AppArmor initialization.
         Starting Load AppArmor profiles managed internally by snapd...
[[0;32m  OK  [0m] Started Load AppArmor profiles managed internally by snapd.
[[0;32m  OK  [0m] Found device 82540EM Gigabit Ethern...r (PRO/1000 MT Desktop Adapter).
[[0;32m  OK  [0m] Found device 82540EM Gigabit Ethern...r (PRO/1000 MT Desktop Adapter).
[   11.416817] cloud-init[471]: Cloud-init v. 21.1-19-gbad84ad4-0ubuntu1~16.04.2 running 'init-local' at Wed, 10 Aug 2022 12:34:28 +0000. Up 11.11 seconds.
[   11.426096] cloud-init[471]: 2022-08-10 12:34:28,588 - util.py[WARNING]: Failed to mount /dev/sdb when looking for data
[   11.554426] cloud-init[471]: 2022-08-10 12:34:28,726 - DataSourceOpenNebula.py[WARNING]: /dev/sdb was not mountable
[[0;32m  OK  [0m] Started Initial cloud-init job (pre-networking).
[[0;32m  OK  [0m] Reached target Network (Pre).
[[0;32m  OK  [0m] Started ifup for enp0s8.
         Starting Raise network interfaces...
[[0;32m  OK  [0m] Started ifup for enp0s3.
[[0;32m  OK  [0m] Started Raise network interfaces.
         Starting Initial cloud-init job (metadata service crawler)...
[[0;32m  OK  [0m] Reached target Network.
[   12.438765] cloud-init[1063]: Cloud-init v. 21.1-19-gbad84ad4-0ubuntu1~16.04.2 running 'init' at Wed, 10 Aug 2022 12:34:29 +0000. Up 12.29 seconds.
[   12.446879] cloud-init[1063]: ci-info: ++++++++++++++++++++++++++++++++++++++Net device info+++++++++++++++++++++++++++++++++++++++
[   12.454578] cloud-init[1063]: ci-info: +--------+------+-----------------------------+---------------+--------+-------------------+
[   12.462840] cloud-init[1063]: ci-info: | Device |  Up  |           Address           |      Mask     | Scope  |     Hw-Address    |
[   12.473715] cloud-init[1063]: ci-info: +--------+------+-----------------------------+---------------+--------+-------------------+
[   12.484028] cloud-init[1063]: ci-info: | enp0s3 | True |          10.0.2.15          | 255.255.255.0 | global | 02:be:82:6b:cc:1d |
[   12.494806] cloud-init[1063]: ci-info: | enp0s3 | True |  fe80::be:82ff:fe6b:cc1d/64 |       .       |  link  | 02:be:82:6b:cc:1d |
[   12.504515] cloud-init[1063]: ci-info: | enp0s8 | True |        192.168.56.11        | 255.255.255.0 | global | 08:00:27:77:6f:9f |
[   12.513973] cloud-init[1063]: ci-info: | enp0s8 | True | fe80::a00:27ff:fe77:6f9f/64 |       .       |  link  | 08:00:27:77:6f:9f |
[   12.523323] cloud-init[1063]: ci-info: |   lo   | True |          127.0.0.1          |   255.0.0.0   |  host  |         .         |
[   12.533072] cloud-init[1063]: ci-info: |   lo   | True |           ::1/128           |       .       |  host  |         .         |
[   12.545371] cloud-init[1063]: ci-info: +--------+------+-----------------------------+---------------+--------+-------------------+
[   12.553859] cloud-init[1063]: ci-info: ++++++++++++++++++++++++++++Route IPv4 info++++++++++++++++++++++++++++
[   12.563070] cloud-init[1063]: ci-info: +-------+--------------+----------+---------------+-----------+-------+
[   12.572806] cloud-init[1063]: ci-info: | Route | Destination  | Gateway  |    Genmask    | Interface | Flags |
[   12.583167] cloud-init[1063]: ci-info: +-------+--------------+----------+---------------+-----------+-------+
[   12.593023] cloud-init[1063]: ci-info: |   0   |   0.0.0.0    | 10.0.2.2 |    0.0.0.0    |   enp0s3  |   UG  |
[   12.601257] cloud-init[1063]: ci-info: |   1   |   10.0.2.0   | 0.0.0.0  | 255.255.255.0 |   enp0s3  |   U   |
[   12.610111] cloud-init[1063]: ci-info: |   2   | 192.168.56.0 | 0.0.0.0  | 255.255.255.0 |   enp0s8  |   U   |
[   12.620737] cloud-init[1063]: ci-info: +-------+--------------+----------+---------------+-----------+-------+
[   12.631598] cloud-init[1063]: ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
[   12.641994] cloud-init[1063]: ci-info: +-------+-------------+---------+-----------+-------+
[   12.651906] cloud-init[1063]: ci-info: | Route | Destination | Gateway | Interface | Flags |
[   12.661271] cloud-init[1063]: ci-info: +-------+-------------+---------+-----------+-------+
[   12.669796] cloud-init[1063]: ci-info: |   0   |  fe80::/64  |    ::   |   enp0s8  |   U   |
[   12.678123] cloud-init[1063]: ci-info: |   1   |  fe80::/64  |    ::   |   enp0s3  |   U   |
[   12.686424] cloud-init[1063]: ci-info: |   4   |   ff00::/8  |    ::   |   enp0s8  |   U   |
[   12.693694] cloud-init[1063]: ci-info: |   5   |   ff00::/8  |    ::   |   enp0s3  |   U   |
[   12.701084] cloud-init[1063]: ci-info: +-------+-------------+---------+-----------+-------+
[   12.708712] cloud-init[1063]: 2022-08-10 12:34:29,610 - util.py[WARNING]: Failed to mount /dev/sdb when looking for data
[   13.760330] cloud-init[1063]: 2022-08-10 12:34:30,931 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [1/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ec22b940>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   15.766851] cloud-init[1063]: 2022-08-10 12:34:32,938 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [3/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631160>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   17.769652] cloud-init[1063]: 2022-08-10 12:34:34,941 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [5/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ec21a748>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   19.774377] cloud-init[1063]: 2022-08-10 12:34:36,946 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [7/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631160>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   21.779142] cloud-init[1063]: 2022-08-10 12:34:38,951 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [9/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631908>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   23.782108] cloud-init[1063]: 2022-08-10 12:34:40,953 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [11/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63b160>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   26.786021] cloud-init[1063]: 2022-08-10 12:34:43,957 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [14/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63b978>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   29.790399] cloud-init[1063]: 2022-08-10 12:34:46,962 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [17/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631d68>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   32.794415] cloud-init[1063]: 2022-08-10 12:34:49,966 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [20/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631400>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   35.797881] cloud-init[1063]: 2022-08-10 12:34:52,969 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [23/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63b198>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   38.801672] cloud-init[1063]: 2022-08-10 12:34:55,973 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [26/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee6421d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   42.806394] cloud-init[1063]: 2022-08-10 12:34:59,978 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [30/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63bc88>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   45.813792] cloud-init[1063]: 2022-08-10 12:35:02,985 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [33/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ec22be80>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   48.820907] cloud-init[1063]: 2022-08-10 12:35:05,993 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [36/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631160>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   52.826520] cloud-init[1063]: 2022-08-10 12:35:09,998 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [40/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631b38>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   55.832355] cloud-init[1063]: 2022-08-10 12:35:13,004 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [43/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee6429e8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   60.841643] cloud-init[1063]: 2022-08-10 12:35:18,013 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [48/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee648240>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   65.849622] cloud-init[1063]: 2022-08-10 12:35:23,021 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [53/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631b38>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   70.858014] cloud-init[1063]: 2022-08-10 12:35:28,029 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [58/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631518>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   75.862309] cloud-init[1063]: 2022-08-10 12:35:33,034 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [63/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63bda0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   80.870013] cloud-init[1063]: 2022-08-10 12:35:38,041 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [68/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee648160>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   86.878213] cloud-init[1063]: 2022-08-10 12:35:44,050 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [74/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee648a58>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   92.886481] cloud-init[1063]: 2022-08-10 12:35:50,058 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [80/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63bb38>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[   98.895471] cloud-init[1063]: 2022-08-10 12:35:56,067 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [86/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee642748>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[  104.902175] cloud-init[1063]: 2022-08-10 12:36:02,074 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [92/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631c88>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[  110.909863] cloud-init[1063]: 2022-08-10 12:36:08,081 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [98/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee6480f0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[  117.918316] cloud-init[1063]: 2022-08-10 12:36:15,090 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [105/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee64f2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[  124.926276] cloud-init[1063]: 2022-08-10 12:36:22,098 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [112/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631dd8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[  130.935463] cloud-init[1063]: 2022-08-10 12:36:28,107 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [118/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /2009-04-04/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee642a20>: Failed to establish a new connection: [Errno 101] Network is unreachable',))]
[  136.942528] cloud-init[1063]: 2022-08-10 12:36:34,114 - DataSourceEc2.py[CRITICAL]: Giving up on md from ['http://169.254.169.254/2009-04-04/meta-data/instance-id'] after 124 seconds
[  138.961925] cloud-init[1063]: 2022-08-10 12:36:36,133 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [2/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63b898>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  141.969231] cloud-init[1063]: 2022-08-10 12:36:39,140 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [5/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee64f4a8>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  144.979829] cloud-init[1063]: 2022-08-10 12:36:42,151 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [8/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee64fc88>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  147.988284] cloud-init[1063]: 2022-08-10 12:36:45,160 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [11/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63bd68>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  150.995914] cloud-init[1063]: 2022-08-10 12:36:48,167 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [14/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631c18>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  154.002834] cloud-init[1063]: 2022-08-10 12:36:51,174 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [17/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee64f1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  158.012325] cloud-init[1063]: 2022-08-10 12:36:55,184 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [21/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee65a4e0>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  162.021647] cloud-init[1063]: 2022-08-10 12:36:59,193 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [25/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee64feb8>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  166.033173] cloud-init[1063]: 2022-08-10 12:37:03,205 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [29/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee631978>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  170.042485] cloud-init[1063]: 2022-08-10 12:37:07,214 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [33/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ec22bd68>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  174.051846] cloud-init[1063]: 2022-08-10 12:37:11,223 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [37/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63bda0>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  179.063816] cloud-init[1063]: 2022-08-10 12:37:16,235 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [42/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee65acf8>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  184.072907] cloud-init[1063]: 2022-08-10 12:37:21,244 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [47/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee5e2550>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  189.083111] cloud-init[1063]: 2022-08-10 12:37:26,255 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [52/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee65a4e0>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  194.093223] cloud-init[1063]: 2022-08-10 12:37:31,265 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [57/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ec22bc18>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  199.103729] cloud-init[1063]: 2022-08-10 12:37:36,275 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [62/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee64f518>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  205.113305] cloud-init[1063]: 2022-08-10 12:37:42,285 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [68/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee5e2400>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  211.123609] cloud-init[1063]: 2022-08-10 12:37:48,295 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [74/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee5e2d68>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  217.133206] cloud-init[1063]: 2022-08-10 12:37:54,305 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [80/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee64f160>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  223.143582] cloud-init[1063]: 2022-08-10 12:38:00,315 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [86/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ec22bba8>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  229.152671] cloud-init[1063]: 2022-08-10 12:38:06,324 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [92/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee65aba8>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  236.165549] cloud-init[1063]: 2022-08-10 12:38:13,337 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [99/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee5e2358>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  243.184616] cloud-init[1063]: 2022-08-10 12:38:20,356 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [106/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee5ec5c0>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  250.196581] cloud-init[1063]: 2022-08-10 12:38:27,367 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [113/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee65a518>: Failed to establish a new connection: [Errno 111] Connection refused',))]
[  256.205203] cloud-init[1063]: 2022-08-10 12:38:33,377 - url_helper.py[WARNING]: Calling 'http://10.0.2.2/latest/meta-data/instance-id' failed [119/120s]: request error [HTTPConnectionPool(host='10.0.2.2', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f27ee63be80>, 'Connection to 10.0.2.2 timed out. (connect timeout=1.0)'))]
[  261.211117] cloud-init[1063]: 2022-08-10 12:38:38,383 - DataSourceCloudStack.py[CRITICAL]: Giving up on waiting for the metadata from ['http://10.0.2.2/latest/meta-data/instance-id'] after 124 seconds
[  262.084790] cloud-init[1063]: Generating public/private rsa key pair.
[  262.092320] cloud-init[1063]: Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
[  262.101580] cloud-init[1063]: Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
[  262.108961] cloud-init[1063]: The key fingerprint is:
[  262.113320] cloud-init[1063]: SHA256:AHcB8eDXHO9lwvwZqmjtDIRAfObECkR7zzvV+scLRI4 root@web01
[  262.121337] cloud-init[1063]: The key's randomart image is:
[  262.128206] cloud-init[1063]: +---[RSA 2048]----+
[  262.134742] cloud-init[1063]: | oo.o.=oo..      |
[  262.139902] cloud-init[1063]: |  .o.+=+ o =     |
[  262.145515] cloud-init[1063]: |  ..o*o o + = +  |
[  262.152273] cloud-init[1063]: |   ..+.+ = . * o |
[  262.157813] cloud-init[1063]: |      + E + o o  |
[  262.164526] cloud-init[1063]: |       + = .     |
[  262.170683] cloud-init[1063]: |      o = +.     |
[  262.176138] cloud-init[1063]: |       o = .o    |
[  262.181944] cloud-init[1063]: |          +...   |
[  262.187679] cloud-init[1063]: +----[SHA256]-----+
[  262.192946] cloud-init[1063]: Generating public/private dsa key pair.
[  262.198565] cloud-init[1063]: Your identification has been saved in /etc/ssh/ssh_host_dsa_key.
[  262.207133] cloud-init[1063]: Your public key has been saved in /etc/ssh/ssh_host_dsa_key.pub.
[  262.214107] cloud-init[1063]: The key fingerprint is:
[  262.219738] cloud-init[1063]: SHA256:4hDmTKydQchtgLVlzQRgSEokOv4/a1cmXMx3Wn/lPdE root@web01
[  262.226645] cloud-init[1063]: The key's randomart image is:
[  262.233111] cloud-init[1063]: +---[DSA 1024]----+
[  262.238357] cloud-init[1063]: |+O====.          |
[  262.244805] cloud-init[1063]: |B.o*o o          |
[  262.251661] cloud-init[1063]: |+ ..*   o       .|
[  262.257782] cloud-init[1063]: |.. B +   + . o .E|
[  262.263792] cloud-init[1063]: | .. * o S . + ..+|
[  262.272088] cloud-init[1063]: |  .  o + o .   o+|
[  262.277582] cloud-init[1063]: |   .  . +       o|
[  262.283361] cloud-init[1063]: |    .o .         |
[  262.289598] cloud-init[1063]: |    .o+          |
[  262.294405] cloud-init[1063]: +----[SHA256]-----+
[  262.302367] cloud-init[1063]: Generating public/private ecdsa key pair.
[  262.309060] cloud-init[1063]: Your identification has been saved in /etc/ssh/ssh_host_ecdsa_key.
[  262.318382] [[0;32m  OK  [0m] Started Initial cloud-init job (metadata service crawler).
[[0;32m  OK  [0m] Reached target Cloud-config availability.
[[0;32m  OK  [0m] Reached target System Initialization.
         Starting Socket activation for snappy daemon.
cloud-init[[0;32m  OK  [0m] Started Daily apt download activities.
[1063]: Your public key has been saved in /etc/ssh/ssh_host_ecdsa_key.pub.
[[0;32m  OK  [0m] Started ACPI Events Check.
[[0;32m  OK  [0m] Reached target Paths.
[  262.344618]          Starting LXD - unix socket.
[[0;32m  OK  [0m] Listening on ACPID Listen Socket.
[[0;32m  OK  [0m] Started Ubuntu Advantage update messaging.
[[0;32m  OK  [0m] Started Daily Cleanup of Temporary Directories.
[[0;32m  OK  [0m] Started Daily apt upgrade and clean activities.
[[0;32m  OK  [0m] Listening on D-Bus System Message Bus Socket.
[[0;32m  OK  [0m] Listening on UUID daemon activation socket.
[[0;32m  OK  [0m] Started Message of the Day.
[[0;32m  OK  [0m] Reached target Timers.
[[0;32m  OK  [0m] Reached target Network is Online.
cloud-init[1063]: The key fingerprint is:
[  262.385625] cloud-init[1063]: SHA256:FlcMIsKeGmsk9dZDBoZ7kDP+UcUDOc1U/zaMo+eXQvE root@web01
[  262.393041]          Starting iSCSI initiator daemon (iscsid)...
cloud-init[[0;32m  OK  [0m] Listening on Socket activation for snappy daemon.
[[0;32m  OK  [0m] Listening on LXD - unix socket.
[[0;32m  OK  [0m] Reached target Sockets.
[[0;32m  OK  [0m] Reached target Basic System.
         Starting System Logging Service...
[[0;32m  OK  [0m] Started Deferred execution scheduler.
         Starting LSB: MD monitoring daemon...
[[0;32m  OK  [0m] Started FUSE filesystem for LXC.
[[0;32m  OK  [0m] Started ACPI event daemon.
         Starting LSB: Record successful boot for GRUB...
         Starting Snap Daemon...
[1063]: The key's randomart image is:
[[0;32m  OK  [0m] Started Regular background program processing daemon.
[  262.461696] cloud-init[1063]: +---[ECDSA 256]---+
[  262.477386] cloud-init[1063]: |   ++.oO+.oo.    |
[  262.489103] cloud-init[1063]: |  B...*.=. o.    |
[[0;32m  OK  [0m] Started D-Bus System Message Bus.
[  262.494334] cloud-init[1063]: | o B * .... .    |
[  262.520742] cloud-init[1063]: |. = B o  o  .+   |
[  262.529236] cloud-init[1063]: | o B . .S   oo=  |
[  262.535907] cloud-init[1063]: |  + .  .   ..oE. |
[  262.543594] cloud-init[1063]: | .        ...  . |
[  262.559736] cloud-init[1063]: |           o. o  |
[  262.567627] cloud-init[1063]: |            .o   |
[  262.585912] cloud-init[1063]: +----[SHA256]-----+
[  262.591308] cloud-init[1063]: Generating public/private ed25519 key pair.
[  262.597184] cloud-init[1063]: Your identification has been saved in /etc/ssh/ssh_host_ed25519_key.
[  262.606412] cloud-init[1063]: Your public key has been saved in /etc/ssh/ssh_host_ed25519_key.pub.
[  262.613787] cloud-init[1063]: The key fingerprint is:
[  262.620729] cloud-init[1063]: SHA256:puai/C/507Jmcc2nD3lU+7X4VJwq+07Z47A16BW6QAQ root@web01
[  262.629158] cloud-init[1063]: The key's randomart image is:
[  262.635546] cloud-init[1063]: +--[ED25519 256]--+
[  262.649879] cloud-init[1063]: |         E       |
[  262.659217] cloud-init[1063]: |          .      |
[  262.667715]          Starting Accounts Service...
         Starting /etc/rc.local Compatibility...
cloud-init         Starting OpenBSD Secure Shell server...
         Starting Login Service...
         Starting LXD - container startup/shutdown...[1063]: 
[[0;32m  OK  [0m|           .  .  |] Started System Logging Service.
[  262.730307] cloud-init[1063]: |          .  . o.|
[  262.730542] cloud-init[1063]: |        So .. .o+|
[  262.730586] cloud-init[1063]: |      .o. +o. B.=|
[  262.734039] cloud-init[1063]: |     .o+  o=.O O.|
[  262.734384] cloud-init[1063]: | .  +o= . .o* X o|
[  262.734900] cloud-init[1063]: |  oo.B=+   o+* o |
[  262.735423] cloud-init[1063]: +----[SHA256]-----+

[[0;32m  OK  [0m] Started /etc/rc.local Compatibility.
[[0;1;31mFAILED[0m] Failed to start iSCSI initiator daemon (iscsid).
See 'systemctl status iscsid.service' for details.
[[0;32m  OK  [0m] Started Login Service.
[[0;32m  OK  [0m] Started OpenBSD Secure Shell server.
[[0;32m  OK  [0m] Started Unattended Upgrades Shutdown.
         Starting Login to default iSCSI targets...
[[0;32m  OK  [0m] Started LSB: Record successful boot for GRUB.
[[0;1;31mFAILED[0m] Failed to start Login to default iSCSI targets.
See 'systemctl status open-iscsi.service' for details.
[[0;32m  OK  [0m] Reached target Remote File Systems (Pre).
         Mounting /vagrant...
[[0;32m  OK  [0m] Started LSB: MD monitoring daemon.
         Starting Authenticate and Authorize Users to Run Privileged Tasks...
[[0;1;31mFAILED[0m] Failed to mount /vagrant.
See 'systemctl status vagrant.mount' for details.
[[0;1;33mDEPEND[0m] Dependency failed for Remote File Systems.
         Starting LSB: Set the CPU Frequency Scaling governor to "ondemand"...
         Starting Permit User Sessions...
         Starting LSB: daemon to balance interrupts for SMP systems...
         Starting LSB: automatic crash report generation...
[[0;32m  OK  [0m] Started Permit User Sessions.
         Starting Terminate Plymouth Boot Screen...
         Starting Hold until boot process finishes up...
[[0;32m  OK  [0m] Started LSB: Set the CPU Frequency Scaling governor to "ondemand".
[[0;32m  OK  [0m] Started Terminate Plymouth Boot Screen.
[[0;32m  OK  [0m] Started Hold until boot process finishes up.
[[0;32m  OK  [0m] Started LXD - container startup/shutdown.
[[0;32m  OK  [0m] Started Authenticate and Authorize Users to Run Privileged Tasks.
[[0;32m  OK  [0m] Started Accounts Service.
[[0;32m  OK  [0m] Created slice User Slice of vagrant.
         Starting User Manager for UID 1000...
         Starting Set console scheme...
[[0;32m  OK  [0m] Started Serial Getty on ttyS0.
[[0;32m  OK  [0m] Started Getty on tty1.
[[0;32m  OK  [0m] Reached target Login Prompts.
[[0;32m  OK  [0m] Started User Manager for UID 1000.
[[0;32m  OK  [0m] Started LSB: daemon to balance interrupts for SMP systems.
[[0;32m  OK  [0m] Started LSB: automatic crash report generation.
[[0;32m  OK  [0m] Started Set console scheme.
[[0;32m  OK  [0m] Started Session 1 of user vagrant.
[[0;32m  OK  [0m] Started Snap Daemon.
         Starting Wait until snapd is fully seeded...
[[0;32m  OK  [0m] Started Wait until snapd is fully seeded.
         Starting Apply the settings specified in cloud-config...
[[0;32m  OK  [0m] Reached target Multi-User System.
[[0;32m  OK  [0m] Reached target Graphical Interface.
         Starting Update UTMP about System Runlevel Changes...
[[0;32m  OK  [0m] Started Update UTMP about System Runlevel Changes.
[  265.428862] cloud-init[1339]: Cloud-init v. 21.1-19-gbad84ad4-0ubuntu1~16.04.2 running 'modules:config' at Wed, 10 Aug 2022 12:38:41 +0000. Up 264.55 seconds.
[[0;32m  OK  [0m] Started Apply the settings specified in cloud-config.
         Starting Execute cloud user/final scripts...
ci-info: no authorized SSH keys fingerprints found for user ubuntu.
<14>Aug 10 12:38:43 ec2: 
<14>Aug 10 12:38:43 ec2: #############################################################
<14>Aug 10 12:38:43 ec2: -----BEGIN SSH HOST KEY FINGERPRINTS-----
<14>Aug 10 12:38:43 ec2: 1024 SHA256:4hDmTKydQchtgLVlzQRgSEokOv4/a1cmXMx3Wn/lPdE root@web01 (DSA)
<14>Aug 10 12:38:43 ec2: 256 SHA256:FlcMIsKeGmsk9dZDBoZ7kDP+UcUDOc1U/zaMo+eXQvE root@web01 (ECDSA)
<14>Aug 10 12:38:43 ec2: 256 SHA256:puai/C/507Jmcc2nD3lU+7X4VJwq+07Z47A16BW6QAQ root@web01 (ED25519)
<14>Aug 10 12:38:43 ec2: 2048 SHA256:AHcB8eDXHO9lwvwZqmjtDIRAfObECkR7zzvV+scLRI4 root@web01 (RSA)
<14>Aug 10 12:38:43 ec2: -----END SSH HOST KEY FINGERPRINTS-----
<14>Aug 10 12:38:43 ec2: #############################################################
-----BEGIN SSH HOST KEY KEYS-----
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJBCqAY4Il+alj6ZPXR1894iSHHaS1bVbZDqdWDeq2eLiPEcQHwzGchOil1UBhsfLQw4AQhQm9tSZqEUIa4n1Yw= root@web01
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICuiGcxeE+3OOcjIQWNUlQoPr3rnIGZH8MxilF/MAwx4 root@web01
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCofVGNsxLxDH7dqseNGeUvPQCjjxtYVLz80TWel5b9ngw0q/xzHVDBqThzAx2L4MJzkmPz1F4XC/ESaZ5KPcJ4PDkk+1LoISbubpeowyqpv8Qtm0jaZexLg/qMpwx44Dy0ViArYB9xk7t+JG1V+rnKUG4sno4IVQ6gI6HegLCf03FvfhNqCdI2TlphTVjw4El79B7LldEemfVBXBcfg70GOzER6+ua+kbQOCbwU8gEsnBdvkHtPmBInw1aXis8rRuJIM1QMa8h+l/RE0KvmA2w15DFeOe8B0RcG9eqzVwNvBT9/I5IQFtYYRkeO+syypya4hXqFnebAyCXS1OPhMIb root@web01
-----END SSH HOST KEY KEYS-----
[  266.244831] cloud-init[1415]: Cloud-init v. 21.1-19-gbad84ad4-0ubuntu1~16.04.2 running 'modules:final' at Wed, 10 Aug 2022 12:38:43 +0000. Up 265.95 seconds.
[  266.272506] cloud-init[1415]: ci-info: no authorized SSH keys fingerprints found for user ubuntu.
[  266.282475] cloud-init[1415]: Cloud-init v. 21.1-19-gbad84ad4-0ubuntu1~16.04.2 finished at Wed, 10 Aug 2022 12:38:43 +0000. Datasource DataSourceNone.  Up 266.23 seconds
[  266.309413] cloud-init[1415]: 2022-08-10 12:38:43,416 - cc_final_message.py[WARNING]: Used fallback datasource
[[0;32m  OK  [0m] Started Execute cloud user/final scripts.
[[0;32m  OK  [0m] Reached target Cloud-init target.

Ubuntu 16.04.7 LTS web01 ttyS0

web01 login: 